### ISSUE TITLE
pretty_print()

### ISSUE THREAD

**Issue by x3ng1n33r** [veewee/xml#85]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 4.0.0
| PHP         | 8.4.1
| PHPUnit     | 11.4.4 (PCOV 1.0.12)

#### Summary

`pretty_print()` does not work as expected in the following [example](https://github.com/veewee/xml/blob/4.x/docs/encoding.md#xml_encode):

```php
use function VeeWee\Xml\Dom\Configurator\pretty_print;
use function VeeWee\Xml\Dom\Configurator\utf8;
use function VeeWee\Xml\Encoding\xml_encode;

$xmlString = xml_encode(['data' => ['hello' => 'world']], utf8(), pretty_print());
```

##### Exception Message

> XML fragment is not well-formed
[FATAL] : Start tag expected, '<' not found
 (4) on line 2,1

##### Exception Trace

```
#0 /var/www/html/composer/veewee/xml/src/Xml/Encoding/Internal/wrap_exception.php(25): VeeWee\Xml\Encoding\Exception\EncodingException::wrapException(Object(VeeWee\Xml\Exception\RuntimeException))
#1 /var/www/html/composer/veewee/xml/src/Xml/Encoding/document_encode.php(21): VeeWee\Xml\Encoding\Internal\wrap_exception(Object(Closure))
#2 /var/www/html/composer/veewee/xml/src/Xml/Encoding/xml_encode.php(20): VeeWee\Xml\Encoding\document_encode(Array, Object(Closure), Object(Closure))
#3 /var/www/html/composer/veewee/xml/src/Xml/Encoding/Internal/wrap_exception.php(23): {closure:VeeWee\Xml\Encoding\xml_encode():19}()
#4 /var/www/html/composer/veewee/xml/src/Xml/Encoding/xml_encode.php(18): VeeWee\Xml\Encoding\Internal\wrap_exception(Object(Closure))
#5 ...: VeeWee\Xml\Encoding\xml_encode(Array, Object(Closure), Object(Closure))
...
```

#### Expected behaviour

Same as version `^3`.

**Comment by veewee** [comment]
Thanks for reporting.

It's been fixed and tagged:
https://github.com/veewee/xml/releases/tag/4.1.0
